### ISSUE TITLE
Sim crash

### ISSUE THREAD

**Issue by lforleee2004** [llamaXc/SaitekPanelMSFS2020#1]
Crash when you unplug pannel but it works brill

**Comment by llamaXc** [comment]
Unable to reproduce. I flew around, flipped some switches, then unplugged the usb panel. MSFS still responded and did not crash. I will keep an eye out on this issue

**Comment by lforleee2004** [comment]
fixed all working good now! cant find any more bugs so good work, i appreciate it. 👍
